import java.util.Random;

/**
 * 27.03.2021
 * Zukhra
 *
 * @author Sidikov Marsel (First Software Engineering Platform)
 * @version v1.0
 */
public class HumansGenerator {
    // статическое поле - оно относится не к объекту, а к классу, следовательно оно может быть только в одном экземпляре
    static String lastNames[] = {
            "Sanchez",
            "Bell",
            "Thompson",
            "Martin",
            "Gray",
            "Murphy",
            "Rogers",
            "Griffin",
            "Gray",
            "Washington",
            "Price",
            "Brown",
            "Hernandez",
            "Washington",
            "Brown",
            "Turner",
            "Martin",
            "Adams",
            "Williams",
            "White",
            "Turner",
            "Morgan",
            "Jackson",
            "King",
            "Thomas",
            "Watson",
            "Thomas",
            "Wood",
            "Alexander",
            "Walker",
            "Hughes",
            "Campbell",
            "Ward",
            "Wood",
            "Howard",
            "Diaz",
            "Gonzalez",
            "Perry",
            "Flores",
            "Alexander",
            "Hill",
            "Flores",
            "Wilson",
            "Collins",
            "Thompson",
            "Hill",
            "Scott",
            "Griffin",
            "Garcia",
            "Alexander",
            "Gonzales",
            "Butler",
            "King",
            "Sanders",
            "Foster",
            "Robinson",
            "Clark",
            "Gray",
            "Rodriguez",
            "Hayes",
            "Patterson",
            "Green",
            "Baker",
            "Allen",
            "Cooper",
            "Moore",
            "White",
            "Martin",
            "Henderson",
            "Bailey",
            "Cook",
            "Hernandez",
            "Young",
            "Bailey",
            "Williams",
            "Barnes",
            "Patterson",
            "Martin",
            "Ramirez",
            "Barnes",
            "Mitchell",
            "Martin",
            "Green",
            "Brown",
            "Perry",
            "Morgan",
            "Richardson",
            "Hill",
            "Howard",
            "Hall",
            "Foster",
            "Sanders",
            "Allen",
            "Richardson",
            "Sanders",
            "Anderson",
            "Edwards",
            "Cook",
            "Washington"
    };

    static String firstNames[] = {
            "Amir",
            "Umer",
            "Charles",
            "Ubaldo",
            "Fitzgerald",
            "Quintin",
            "Roland",
            "Rodrigo",
            "Wells",
            "Tobias",
            "Promise",
            "Ford",
            "Jose",
            "Diego",
            "Jesus",
            "Luka",
            "Gunnar",
            "Joseph",
            "Jase",
            "Issac",
            "Raiden",
            "Adam",
            "Marshall",
            "Nickolas",
            "Clayton",
            "Huxley",
            "Leonard",
            "Finley",
            "Arlo",
            "Yousuf",
            "Xeno",
            "Jaxson",
            "Fitzgerald",
            "Gunnar",
            "Zechariah",
            "Henley",
            "Issa",
            "Dominick",
            "Promise",
            "Hadlee",
            "Yahya",
            "Leonard",
            "Fletcher",
            "Ubaldo",
            "Westin",
            "Irvin",
            "Nick",
            "Nathaniel",
            "Solomon",
            "Verney",
            "Jaxson",
            "Nikhil",
            "Quintan",
            "Ezekiel",
            "Xaviero",
            "Niklaus",
            "Jake",
            "Harry",
            "Presleigh",
            "Kane",
            "Ryker",
            "Martin",
            "Philip",
            "Vicente",
            "Diego",
            "Umer",
            "Moses",
            "Oaklee",
            "Quentrell",
            "Isidro",
            "Fischer",
            "Fabian",
            "Gage",
            "Xander",
            "Jax",
            "Stephen",
            "Quinntin",
            "Pembroke",
            "Westin",
            "Nasir",
            "Gordon",
            "Oren",
            "Will",
            "Emery",
            "Preston",
            "Orlando",
            "Frederick",
            "Kylan",
            "Zack",
            "Tyrone",
            "Yehoshua",
            "Yousef",
            "Kinslee",
            "Ismail",
            "Quinntin",
            "Harris",
            "Gordon",
            "Israel",
            "Ulrich",
    };

    Human[] generate(int humansCount, int maxAge) {
        Random random = new Random();

        Human humans[] = new Human[humansCount];

        for (int i = 0; i < humans.length; i++) {
            int randomFirstNameIndex = random.nextInt(firstNames.length);
            int randomLastNameIndex = random.nextInt(lastNames.length);
            // получил случайное имя из массива
            String randomFirstName = firstNames[randomFirstNameIndex];
            // получил случайную фамилию из массива
            String randomLastName = lastNames[randomLastNameIndex];
                Human newHuman = new Human(random.nextInt(maxAge), randomFirstName + " " + randomLastName);
            humans[i] = newHuman;
        }

        return humans;
    }
}
